[build]
builder = "NIXPACKS"
# Nixpacks debería detectar tu requirements.txt y Procfile automáticamente.
# Pero podemos añadir un comando de construcción explícito si es necesario.
#buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn backend_analytics_server.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 120